workflows:
  ios-build:
    name: iOS MVP Build
    instance_type: mac_mini_m2
    environment:
      flutter: 3.44.9
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter packages pub get
      - name: Build iOS IPA (Unsigned)
        script: |
          # Compilation de l'application sans signature (crée un .app)
          flutter build ios --release --no-codesign
          
          # Création manuelle du fichier .ipa pour Sideloadly
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -qr rayban_mvp_unsigned.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
